### PR TITLE
Controlled row selection

### PR DESCRIPTION
**Pull request by dmitriy-kudelko**
This PR implements controlled row selection to enable passing an array of selected row ids from outside.

It also:
- includes some code refactoring to avoid anti-patterns such as setting state in `CDM`.
- Fixes prop type validation of Cell.id prop

### CODE REVIEW

**Comment by dmitriy-kudelko** [comment]
@samrith-s , please check this as soon as you can. We need to publish this.

**Review by samrith-s — APPROVED** [review]
@dmitriy-kudelko  Looks good. Tested it, works as expected.

On another note, why are we maintaining `checkedRows` and `selectedRows`? Should we rather only keep one thing (ideally `selectedRows`)?

**Comment by dmitriy-kudelko** [comment]
@samrith-s , we actually maintain either one or another, but not both. This is done mainly to avoid mirroring `checkedRows` (or `selectedRows` - depending on which name we choose) in state when it's controlled - which is considered to be an anti-pattern.

`checkedRows` basically serves as uncontrolled variation which probably might be useful in some rare cases.

**Comment by samrith-s** [comment]
Cool, makes sense. I was just thinking about this mimicking the way controlled/uncontrolled components work.

**Pull request merged**
